### ISSUE TITLE
Error with less than 15 colums/fields

### ISSUE THREAD

**Issue by BjoMei** [profiler/HB_Convert#1]
Hy,

first of all: Thanks for your work. 

The csv Files of my bank have just 11 colums. But HB_convert seems to need at least 15 colums. 

Her is my log:
Opening import     <open file 'in2.csv', mode 'r' at 0xb7765338>
        export     <open file 'out.csv', mode 'w' at 0xb7765390>
        definition <open file 'Sparkasse.def', mode 'r' at 0xb77653e8>
Error in record[2]: Field(s) missing
Error in record[3]: Field(s) missing
Error in record[4]: Field(s) missing
Error in record[5]: Field(s) missing
Error in record[6]: Field(s) missing
Error in record[7]: Field(s) missing
Error in record[8]: Field(s) missing
Error in record[9]: Field(s) missing
Error in record[10]: Field(s) missing
Error in record[11]: Field(s) missing
Error in record[12]: Field(s) missing
Error in record[13]: Field(s) missing
Error in record[14]: Field(s) missing
Error in record[15]: Field(s) missing
Error in record[16]: Field(s) missing
Error in record[17]: Field(s) missing
Error in record[18]: Field(s) missing
Closing files

Everything is running fine if I add ";;;;;;;" at the end of every line. 

Is this a bug?
How can I handle it?

Thanks,
B.Meier

**Comment by BjoMei** [comment]
Sorry profiler,

it's not a bug !! It was my fault.

In my def file i wrote lines like this ones:
4;description   ;-1;Description.2  ;
4;description   ;-1;Description.3  ;
4;description   ;-1;                     ;
4;description   ;-1;                     ;
4;description   ;-1;                    ;

After deleting this lines, everthing is running fine.

If my defs (maybe four banks) are all testet and running fine, do you want to host them for other users?

B.Meier

**Comment by profiler** [comment]
@B.Meier,
Good to hear you found it yourself and that it all works fine. Well this little program does not check everything yet. Maybe I could complete the parser to give more specific error messages one day.
Yes, you mean that you can send an example of your bank-files (CSV and  DEF), please do. This way I can get an idea of the variety of bank-csv export files. >>> BE SURE TO DISGUISE PERSONAL DATA. 

Profiler
