### ISSUE TITLE
Fixed acount for a definition

### ISSUE THREAD

**Issue by BjoMei** [profiler/HB_Convert#2]
Hi profiler,

first of all: Thanks for your work !! 

And now my issue;
In my situation I have a fixed mapping between every definition and a associated account. 
Example: def 1 -> acount 1, def 2 -> acount2, ....
But the name of my acounts is not in the input.csv ' s.
Therefore, it would be nice if I could specify in any definition a fixed account without the name is present in the input.csv.

Lots of greetings,
from a happy "Homebank" user

**Comment by profiler** [comment]
@ Homebank:
The account name/number is not implemented yet in the Homebank-import function.
At the moment the imported csv-content is not automaticly linked to the right Homebank-account.
And from what I understand, you don't have "multi-account" files.
Already included in this script is a list of all your known bank-accounts.
Look inside Convert.py  where the "parse import.csv" starts.

```
    bank = {                                # All known accounts
    '0123456789':'Bank1',
    '0987654321':'Bank2'
    }
```

And include your personal [account-number] and [homebank-name] here.

greetings
Profiler
