### ISSUE TITLE
start convert in line n

### ISSUE THREAD

**Issue by BjoMei** [profiler/HB_Convert#3]
Hi profiler,

and an other issue:

I have a input.csv where the booking lines starts in line 8. And not in line 1 or 2.

Example:
[start input.csv]
"Kontonummer:";"123456789 / Internet-Konto";

"Von:";"12.05.2010";
"Bis:";"12.05.2011";
"Kontostand vom:";"123,45";

"Buchungstag";"Wertstellung";"Buchungstext";"Auftraggeber/Begünstigter";"Verwendungszweck";"Kontonummer";"BLZ";"Betrag (EUR)";
"02.05.2011";"02.05.2011";"DAUERAUFTRAG";"MKB VISAMARD";"123456789 MAX MUSTERMANN MKB INTERNET BANKING ";"12345678";"12345678";"-345,67";
[/end input.csv]

It would be great if I could define that the conversion starts in line 8 !!

Bye
a happy "homebank" user

**Comment by profiler** [comment]
Hi,
Starting at an specific line-number is maybe not the best solution for an universal converter, because this issue only exits because the script does not allow empty-lines inside the import-file. I will look into it.

Greetings
Profiler

**Comment by profiler** [comment]
@ Homebank:
If have found a way to be able to incorporate parsing of CSV-files with header.
If you are interested let me know.

Greetings
Profiler
